//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineBankingApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NetBanking
    {
        public int UserID { get; set; }
        public string LoginPassword { get; set; }
        public string TransactionPassword { get; set; }
    
        public virtual User User { get; set; }
    }
}
